name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: Get 00.m3u8
      run: |
        touch ./00.m3u8
        sudo cat >./00.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-TARGETDURATION:5
        #EXT-X-DISCONTINUITY-SEQUENCE:785
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -f best -g https://www.youtube.com/watch?v=wKjPli-AHdA)
        EOL
    - name: Get 01.m3u8
      run: |
        touch ./01.m3u8
        sudo cat >./01.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-TARGETDURATION:5
        #EXT-X-DISCONTINUITY-SEQUENCE:785
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -f best -g https://www.youtube.com/watch?v=GCqbjyMGrXs)
        EOL
    - name: Get 09.m3u8
      run: |
        touch ./09.m3u8
        sudo cat >./09.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=oV_i3Hsl_zg)
        EOL
    - name: Get 13.m3u8
      run: |
        touch ./13.m3u8
        sudo cat >./13.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=JAzRXylm3M0)
        EOL
    - name: Get 14.m3u8
      run: |
        touch ./14.m3u8
        sudo cat >./14.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=cnYQ_z7QfxE)
        EOL
    - name: Get 34.m3u8
      run: |
        touch ./34.m3u8
        sudo cat >./34.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=_Vlzn9qAHD4)
        EOL
    - name: Get 35.m3u8
      run: |
        touch ./35.m3u8
        sudo cat >./35.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=xbNWkUyxQGM)
        EOL
    - name: Get 46.m3u8
      run: |
        touch ./46.m3u8
        sudo cat >./46.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=Z50JFuNgvB0)
        EOL
    - name: Get 47.m3u8
      run: |
        touch ./47.m3u8
        sudo cat >./47.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=ViJ3XiN6Q3M)
        EOL
    - name: Get 48.m3u8
      run: |
        touch ./48.m3u8
        sudo cat >./48.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=_pZQ1Lk0xMA)
        EOL
    - name: Get 51.m3u8
      run: |
        touch ./51.m3u8
        sudo cat >./51.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=R2iMq5LKXco)
        EOL
    - name: Get 52.m3u8
      run: |
        touch ./52.m3u8
        sudo cat >./52.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=lu_BJKxqGnk)
        EOL
    - name: Get 53.m3u8
      run: |
        touch ./53.m3u8
        sudo cat >./53.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=XGEmg3vhrzU)
        EOL
    - name: Get 54.m3u8
      run: |
        touch ./54.m3u8
        sudo cat >./54.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=FoBfXvlOR6I)
        EOL
    - name: Get 55.m3u8
      run: |
        touch ./55.m3u8
        sudo cat >./55.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=2mCSYvcfhtc)
        EOL
    - name: Get 56.m3u8
      run: |
        touch ./56.m3u8
        sudo cat >./56.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-TARGETDURATION:5
        #EXT-X-MEDIA-SEQUENCE:2698190
        #EXT-X-DISCONTINUITY-SEQUENCE:532
        $(youtube-dl -f best --hls-prefer-native --hls-use-mpegts --fixup warn -g https://www.youtube.com/watch?v=hP6_jfCFxyQ)
        EOL
    - name: Get 57.m3u8
      run: |
        touch ./57.m3u8
        sudo cat >./57.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=ABn_ccXn_jc)
        EOL
    - name: Get 59.m3u8
      run: |
        touch ./59.m3u8
        sudo cat >./59.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/watch?v=yuhgIlXwPh8)
        EOL
    - name: Get 60.m3u8
      run: |
        touch ./60.m3u8
        sudo cat >./60.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=u0NYyH3ZesE)
        EOL
    - name: Get 86.m3u8
      run: |
        touch ./86.m3u8
        sudo cat >./86.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/watch?v=I1TUDXaEnbE)
        EOL
    - name: Get 89.m3u8
      run: |
        touch ./89.m3u8
        sudo cat >./89.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=CKjSm5ZeehE)
        EOL
    - name: Get 92.m3u8
      run: |
        touch ./92.m3u8
        sudo cat >./92.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=qX1W7lZQp5A)
        EOL
    - name: Get 93.m3u8
      run: |
        touch ./93.m3u8
        sudo cat >./93.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=n2d_EUCnPuE)
        EOL
    - name: Get 94.m3u8
      run: |
        touch ./94.m3u8
        sudo cat >./94.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=n6W3A0CA4WI)
        EOL
    - name: Get 98.m3u8
      run: |
        touch ./98.m3u8
        sudo cat >./98.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=Lde1rqHuUpM)
        EOL
    - name: Get 102.m3u8
      run: |
        touch ./102.m3u8
        sudo cat >./102.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=GlGXdDBGZ7k)
        EOL
    - name: Get 103.m3u8
      run: |
        touch ./103.m3u8
        sudo cat >./103.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=NieKeLd8GLw)
        EOL
    - name: Get 104.m3u8
      run: |
        touch ./104.m3u8
        sudo cat >./104.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=kr77WtxLDBQ)
        EOL
    - name: Get 105.m3u8
      run: |
        touch ./105.m3u8
        sudo cat >./105.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=wSKE3A40SIk)
        EOL
    - name: Get 106.m3u8
      run: |
        touch ./106.m3u8
        sudo cat >./106.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=wldWQnyVwpk)
        EOL
    - name: Get 108.m3u8
      run: |
        touch ./108.m3u8
        sudo cat >./108.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=wSKE3A40SIk)
        EOL
    - name: Get 109.m3u8
      run: |
        touch ./109.m3u8
        sudo cat >./109.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=CHDb5D0DCkw)
        EOL
    - name: Get 110.m3u8
      run: |
        touch ./110.m3u8
        sudo cat >./110.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=5a69HEWyXBE)
        EOL
    - name: Get 115.m3u8
      run: |
        touch ./115.m3u8
        sudo cat >./115.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=u-8-AGemeqc)
        EOL
    - name: Get 116.m3u8
      run: |
        touch ./116.m3u8
        sudo cat >./116.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=zKfOUCq3rW8)
        EOL
    - name: Get 118.m3u8
      run: |
        touch ./118.m3u8
        sudo cat >./118.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=X-vcxpwIY3Q)
        EOL
    - name: Get 119.m3u8
      run: |
        touch ./119.m3u8
        sudo cat >./119.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=fkgDWd38jqQ)
        EOL
    - name: Get 120.m3u8
      run: |
        touch ./120.m3u8
        sudo cat >./120.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=jTS3A4D4x6Q)
        EOL
    - name: Get 121.m3u8
      run: |
        touch ./121.m3u8
        sudo cat >./121.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=LEOat38Iuao)
        EOL
    - name: Get 123.m3u8
      run: |
        touch ./123.m3u8
        sudo cat >./123.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=jRsyBLhot6E)
        EOL
    - name: Get 124.m3u8
      run: |
        touch ./124.m3u8
        sudo cat >./124.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=RAP4h3q6_Sg)
        EOL
    - name: Get 125.m3u8
      run: |
        touch ./125.m3u8
        sudo cat >./125.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=po6M2_jdSdQ)
        EOL
    - name: Get 129.m3u8
      run: |
        touch ./129.m3u8
        sudo cat >./129.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=zNESDscyCmk)
        EOL
    - name: Get 154.m3u8
      run: |
        touch ./154.m3u8
        sudo cat >./154.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=TCnaIE_SAtM)
        EOL
    - name: Get 155.m3u8
      run: |
        touch ./155.m3u8
        sudo cat >./155.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL
    - name: Get 159.m3u8
      run: |
        touch ./159.m3u8
        sudo cat >./159.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=yUTy1U1wTwE)
        EOL
    - name: Get 222.m3u8
      run: |
        touch ./222.m3u8
        sudo cat >./222.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=-s6BflnoCrQ)
        EOL
    - name: Get 297.m3u8
      run: |
        touch ./297.m3u8
        sudo cat >./297.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL
    - name: Get 950.m3u8
      run: |
        touch ./950.m3u8
        sudo cat >./950.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=wrYF0HX7Kzc)
        EOL
    - name: Get 951.m3u8
      run: |
        touch ./951.m3u8
        sudo cat >./951.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=N61GgfVCLKg)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
