name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
    - name: Get 09.m3u8
      run: |
        touch ./09.m3u8
        sudo cat >./09.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g --geo-bypass https://www.youtube.com/watch?v=oV_i3Hsl_zg)
        EOL
    - name: Get 13.m3u8
      run: |
        touch ./13.m3u8
        sudo cat >./13.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g --geo-bypass https://www.youtube.com/watch?v=JAzRXylm3M0)
        EOL
    - name: Get 14.m3u8
      run: |
        touch ./14.m3u8
        sudo cat >./14.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=cnYQ_z7QfxE)
        EOL
    - name: Get 34.m3u8
      run: |
        touch ./34.m3u8
        sudo cat >./34.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=_Vlzn9qAHD4)
        EOL
    - name: Get 35.m3u8
      run: |
        touch ./35.m3u8
        sudo cat >./35.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=xbNWkUyxQGM)
        EOL
    - name: Get 46.m3u8
      run: |
        touch ./46.m3u8
        sudo cat >./46.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=Z50JFuNgvB0)
        EOL
    - name: Get 47.m3u8
      run: |
        touch ./47.m3u8
        sudo cat >./47.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=ViJ3XiN6Q3M)
        EOL
    - name: Get 48.m3u8
      run: |
        touch ./48.m3u8
        sudo cat >./48.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=_pZQ1Lk0xMA)
        EOL
    - name: Get 51.m3u8
      run: |
        touch ./51.m3u8
        sudo cat >./51.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=R2iMq5LKXco)
        EOL
    - name: Get 52.m3u8
      run: |
        touch ./52.m3u8
        sudo cat >./52.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=lu_BJKxqGnk)
        EOL
    - name: Get 53.m3u8
      run: |
        touch ./53.m3u8
        sudo cat >./53.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=XGEmg3vhrzU)
        EOL
    - name: Get 54.m3u8
      run: |
        touch ./54.m3u8
        sudo cat >./54.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=FoBfXvlOR6I)
        EOL
    - name: Get 55.m3u8
      run: |
        touch ./55.m3u8
        sudo cat >./55.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=2mCSYvcfhtc)
        EOL
    - name: Get 56.m3u8
      run: |
        touch ./56.m3u8
        sudo cat >./56.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=hP6_jfCFxyQ)
        EOL
    - name: Get 57.m3u8
      run: |
        touch ./57.m3u8
        sudo cat >./57.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=ABn_ccXn_jc)
        EOL
    - name: Get 59.m3u8
      run: |
        touch ./59.m3u8
        sudo cat >./59.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp -g https://www.youtube.com/watch?v=yuhgIlXwPh8)
        EOL
    - name: Get 60.m3u8
      run: |
        touch ./60.m3u8
        sudo cat >./60.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=u0NYyH3ZesE)
        EOL
    - name: Get 86.m3u8
      run: |
        touch ./86.m3u8
        sudo cat >./86.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=VD8dVG1DF1s)
        EOL
    - name: Get 89.m3u8
      run: |
        touch ./89.m3u8
        sudo cat >./89.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=CKjSm5ZeehE)
        EOL
    - name: Get 92.m3u8
      run: |
        touch ./92.m3u8
        sudo cat >./92.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=7uZuEsKoV78)
        EOL
    - name: Get 94.m3u8
      run: |
        touch ./94.m3u8
        sudo cat >./94.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=O2_-kv1dD1A)
        EOL
    - name: Get 98.m3u8
      run: |
        touch ./98.m3u8
        sudo cat >./98.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=xsD6eA9hglY)
        EOL
    - name: Get 102.m3u8
      run: |
        touch ./102.m3u8
        sudo cat >./102.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=GlGXdDBGZ7k)
        EOL
    - name: Get 104.m3u8
      run: |
        touch ./104.m3u8
        sudo cat >./104.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=kr77WtxLDBQ)
        EOL
    - name: Get 105.m3u8
      run: |
        touch ./105.m3u8
        sudo cat >./105.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=wSKE3A40SIk)
        EOL
    - name: Get 106.m3u8
      run: |
        touch ./106.m3u8
        sudo cat >./106.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=TBHuOAky73I)
        EOL
    - name: Get 109.m3u8
      run: |
        touch ./109.m3u8
        sudo cat >./109.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=CHDb5D0DCkw)
        EOL
    - name: Get 110.m3u8
      run: |
        touch ./110.m3u8
        sudo cat >./110.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=HcPV1cUGiuY)
        EOL
    - name: Get 116.m3u8
      run: |
        touch ./116.m3u8
        sudo cat >./116.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=GutWwlkb4Ic)
        EOL
    - name: Get 118.m3u8
      run: |
        touch ./118.m3u8
        sudo cat >./118.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=0hgUBJEG1Ys)
        EOL
    - name: Get 120.m3u8
      run: |
        touch ./120.m3u8
        sudo cat >./120.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=jTS3A4D4x6Q)
        EOL
    - name: Get 121.m3u8
      run: |
        touch ./121.m3u8
        sudo cat >./121.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=LEOat38Iuao)
        EOL
    - name: Get 123.m3u8
      run: |
        touch ./123.m3u8
        sudo cat >./123.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=jRsyBLhot6E)
        EOL
    - name: Get 124.m3u8
      run: |
        touch ./124.m3u8
        sudo cat >./124.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=RAP4h3q6_Sg)
        EOL
    - name: Get 125.m3u8
      run: |
        touch ./125.m3u8
        sudo cat >./125.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=hBzlSpshEgc)
        EOL
    - name: Get 132.m3u8
      run: |
        touch ./132.m3u8
        sudo cat >./132.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=zNESDscyCmk)
        EOL
    - name: Get 154.m3u8
      run: |
        touch ./154.m3u8
        sudo cat >./154.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=TCnaIE_SAtM)
        EOL
    - name: Get 155.m3u8
      run: |
        touch ./155.m3u8
        sudo cat >./155.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL
    - name: Get 159.m3u8
      run: |
        touch ./159.m3u8
        sudo cat >./159.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=yUTy1U1wTwE)
        EOL
    - name: Get 297.m3u8
      run: |
        touch ./297.m3u8
        sudo cat >./297.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL
    - name: Get 950.m3u8
      run: |
        touch ./950.m3u8
        sudo cat >./950.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=wrYF0HX7Kzc)
        EOL
    - name: Get 951.m3u8
      run: |
        touch ./951.m3u8
        sudo cat >./951.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=s74IEySS_4Y)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
